### ISSUE TITLE
Cannot find codec

### ISSUE THREAD

**Issue by SpyrosPsarras** [jackun/TestAMFVFW#1]
Started a new thread here instead of the openencodevfw.
15.7 catalyst, HD7870, Dxtory doesn't see the teastamf codec too. MSI afterburner too cannot see the codec. Sherlock the codec detective cannot find it too. o.O

**Comment by jackun** [comment]
Copy/paste here too, (inb4 uploaded debug versions): Unpack to some permanent folder and install from there. Check that in registry `HKEY_CURRENT_USER\Software\TestAMFVFW\InstallPath` points to the `Runtimes` folder. Otherwise check with [DW](http://www.dependencywalker.com/), only thing unresolved should be AMF related dlls that are delay-loaded (which is WIP itself) (ignoring ms-api-.... things).

**Comment by eanmclaughlin** [comment]
I installed it (install.bat as Administrator) and DxTory picked it up right away (Windows 10, Catalyst 15.7)

**Comment by SpyrosPsarras** [comment]
Runtimes points to the correct registry key.
TestAMFVFW.dll opened with DW. 
Modules missing :
API-MS-WIN-CORE-KERNEL32-PRIVATE-L1-1-1.DLL
API-MS-WIN-CORE-PRIVATEPROFILE-L1-1-1.DLL
API-MS-WIN-SERVICE-PRIVATE-L1-1-1.DLL
AMF-CORE-WINDESKTOP64.DLL
API-MS-WIN-CORE-SHUTDOWN-L1-1-1.DLL
EXT-MS-WIN-NTUSER-UICONTEXT-EXT-L1-1-0.DLL
IESHIMS.DLL
The installation is performed with admin rights, cause if not errors pop up.

**Comment by jackun** [comment]
@SpyPower seems to be correct. You did right click on `install.bat` and run as admin?

You could also double-check these registry entries:

```
"HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\MediaResources\icm\VIDC.H264\Driver" set to "TestAMFVFW.DLL"
"HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Drivers32\VIDC.H264" set to "TestAMFVFW.DLL"
```

**Comment by SpyrosPsarras** [comment]
@jackun I did right click on install.bat and run as admin. I could not do it without admin privileges. 
Both registry files are there, and set to TestAMFVFW.DLL. 
I am running win8.1 pro x64, and currently upgrading to win10. I will wait till the installation finishes. I offer also some teamviewer experience if you are willing to see. Am I good from dependencies view?

**Comment by Rawi666** [comment]
I have exactly the same situation as SpyPower and the two HKLM reg keys are present.
If you find the solution please post it here.

**Comment by SpyrosPsarras** [comment]
Well, installed w10, installed the codec and boom, it was there on Dxtory 2.0.127. 
Driver Packing Version: 15.20-150715a-184226E
2D Driver Version: 8.01.01.1500
OpenGL Version: 6.14.10.13399
Direct3D Version: 9.14.10.01128
Mantle Driver Version: 9.1.10.0077
Mantle API Version: 98308
AMD Catalyst Control Center Version: 2015.0715.2138.37093
w10 only feature? no idea. shouldn't be the case.

**Comment by AndreJSLC** [comment]
I have windows 8.1 too and dxtory is also not showing this codec.Any fix?

**Comment by jackun** [comment]
@mrsheepmasterdy Be sure to install MSVC++ 2013 runtimes (link in README). There have been some weird cases where windows' side-by-side 'DLL cache' has made games crash etc fixed by reinstalling msvc++. So if it still doesn't show up you may try uninstalling all MSVC++ 2013 runtimes and then reinstall only the latest version.

Other than that, AMF dlls need msvc++2012, i think, but catalyst installs it already anyway.

**Comment by epinox** [comment]
I am using MSI Afterburner. But when I stop recording, the mkv video file shows me only a black screen. Media Player Classic tells me that the video codec is raw format. Using the x264vfw codec work - but it is slow. ;)

My configuration: Windows 10, Radeon R9 380

EDIT 21 Oct: now it works... thanks!
